apiVersion: v1
kind: Service
metadata:
  name: node-api
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http
  - name: debug
    protocol: TCP
    port: 5858
    nodePort: 30886
    targetPort: debug
  selector:
    app: node-api
  type: NodePort
